### ISSUE TITLE
Task canceled error while using secure connection

### ISSUE THREAD

**Issue by stenol** [Toemsel/Network#43]
When I'm using secure connection, as soon as I connect client to server, the server throw a Task canceled error. Here is the trace that appear in the console. If you need more info, just ask me.

-------------------------------------------------
```

'PulsarWindowsService.exe' (CLR v4.0.30319: PulsarWindowsService.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Transactions.resources\v4.0_4.0.0.0_fr_b77a5c561934e089\System.Transactions.resources.dll'. Module was built without symbols.
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Exception non prise en charge</Description><AppDomain>PulsarWindowsService.exe</AppDomain><Exception><ExceptionType>System.Threading.Tasks.TaskCanceledException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Une tâche a été annulée.</Message><StackTrace>   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.Async.ChickenReceiver.&amp;lt;Send&amp;gt;d__2`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.Connection.&amp;lt;SendAsync&amp;gt;d__108`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.RSA.RSAConnection.&amp;lt;ExchangePublicKeys&amp;gt;d__39.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.&amp;lt;&amp;gt;c.&amp;lt;ThrowAsync&amp;gt;b__6_1(Object state)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()</StackTrace><ExceptionString>System.Threading.Tasks.TaskCanceledException: Une tâche a été annulée.
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.Async.ChickenReceiver.&amp;lt;Send&amp;gt;d__2`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.Connection.&amp;lt;SendAsync&amp;gt;d__108`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.RSA.RSAConnection.&amp;lt;ExchangePublicKeys&amp;gt;d__39.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.&amp;lt;&amp;gt;c.&amp;lt;ThrowAsync&amp;gt;b__6_1(Object state)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()</ExceptionString></Exception></TraceRecord>
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Exception non prise en charge</Description><AppDomain>PulsarWindowsService.exe</AppDomain><Exception><ExceptionType>System.Threading.Tasks.TaskCanceledException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Une tâche a été annulée.</Message><StackTrace>   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.Async.ChickenReceiver.&amp;lt;Send&amp;gt;d__2`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.Connection.&amp;lt;SendAsync&amp;gt;d__108`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.RSA.RSAConnection.&amp;lt;ExchangePublicKeys&amp;gt;d__39.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.&amp;lt;&amp;gt;c.&amp;lt;ThrowAsync&amp;gt;b__6_1(Object state)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()</StackTrace><ExceptionString>System.Threading.Tasks.TaskCanceledException: Une tâche a été annulée.
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.Async.ChickenReceiver.&amp;lt;Send&amp;gt;d__2`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.Connection.&amp;lt;SendAsync&amp;gt;d__108`1.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à Network.RSA.RSAConnection.&amp;lt;ExchangePublicKeys&amp;gt;d__39.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.AsyncMethodBuilderCore.&amp;lt;&amp;gt;c.&amp;lt;ThrowAsync&amp;gt;b__6_1(Object state)
   à System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   à System.Threading.ThreadPoolWorkQueue.Dispatch()
   à System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()</ExceptionString></Exception></TraceRecord>
System.Transactions Critical: 0 : An unhandled exception of type 'System.Threading.Tasks.TaskCanceledException' occurred in mscorlib.dll
Une tâche a été annulée.
```
-------------------------

**Comment by Toemsel** [comment]
- Are the private/public keys correct for each kind?
- Is the communication working without RSA?
- Make sure the firewall isn't blocking the connections

Since the GitHub example doesn't throw any exception and the provided stacktrace doesn't help either, I would require a small sample project illustrating the issue.

**Comment by stenol** [comment]
Here is some other info:

- The communication is working without RSA.
- The key lenght of RSA is 512 bits (I know, it's less secure than 2048 bits but it's alright for our purpose)
- The server is use in a windows service application.
- The client is on a xamarin android application with android 6.0 +

I will try to make a small project that illustrate the issue. :)

**Comment by Toemsel** [comment]
An example is required to reconstruct your issue.

Did you try the RSA approach with the default RSA key size? (Just leave it empty so the overloading will take care of it)

**Comment by stenol** [comment]
Here is a link for a demo project. Don't forget to change ip address in Program.cs of the ClientTest project. The main solution file is in the ServerTest folder. I try with 512 and 1024 key size and the issue is there. With 2048 key size, there is no issue.

[http://sjs-studio.com/temp/CrashTaskCancel.zip](url)

**Comment by Toemsel** [comment]
Thanks. Please stick with the 2048 key size as long as there isn't a new NuGet available. Will invest and fix within the next two weeks.

Thanks for your understanding

**Comment by stenol** [comment]
Thank you. Just let me know when it will be ready :)

**Comment by luky92** [comment]
Is there any update on that? i have a simular issiue

**Comment by Toemsel** [comment]
Sorry, not yet. I will investigate that isse as soon as possible. I will raise the priority.

**Comment by Toemsel** [comment]
Issue has been resolved. 

**Improvements**

- Server and Client may choose an arbitrary key size, they can, but don't have to match.
As an example: Only the client sends highly sensitive data and the server only acknowledges.
Server -> Client: 512 keySize
Client -> Server: 4096 keySize
- Invalid key sizes (e.g.: 256) will throw an exception immediately.
- The lib will log performance issues, if the keySize has been chosen too secure
- Small refactorings as well

Please let me know if the release works for you. Thanks

**Comment by luky92** [comment]
the new version has a different error even on default key lenth 
[network.log](https://github.com/Toemsel/Network/files/3745673/network.log)
here is a log

**Comment by Toemsel** [comment]
ok, thanks for the feedback. I will take the current version down from NuGet. Just in case

**Comment by luky92** [comment]
Client Android 6.0 xamarin forms app 
Server Winforms app on win 10
here is a log from the new ver
[network.log](https://github.com/Toemsel/Network/files/3746526/network.log)
i noticed that when switching pages in the app the client reconnects now but it still crashes this dosent happen on plain text connection

**Comment by Toemsel** [comment]
The new exception log seems to be different from the first one, which is odd.
My first guess is the unsupported RSA OAE Padding on Android 6.0.
Could you please re-try the same scenario with the newest SRC commit?

In the meanwhile I will install Xamarin on my machine to reproduce your issue.

**Comment by luky92** [comment]
ok now it creates udp connection for rsa as well
here is a new log
[network.log](https://github.com/Toemsel/Network/files/3747036/network.log)

**Comment by Toemsel** [comment]
I have setup the same environment on my machine.
Without UDP is seems to work fine. Somehow the UDP connection instantly closes after sending data over RSA. Still investigating.

**Comment by luky92** [comment]
ok seems like the firewall was to blame on the last error here is a new one 
[network.log](https://github.com/Toemsel/Network/files/3747046/network.log)

**Comment by Toemsel** [comment]
Now we receive the exact same error :) At least something. Thanks for the report. I will let you know when it has been fixed.

**Comment by Toemsel** [comment]
Try the code out on your device, instead within the emulator.
The RSA communication does work while it runs on a device, but will fail in the emulator.

Please let me know if it also works for you on the device.

**Comment by Toemsel** [comment]
Uppon further investigation the issue arrives from the Android Emulator environment.
There are several open issues on Xamarin regarding unreceivable UDP packets.

Till the issue has been fixed from Xamarin, avoid using UDP within the emulator, or simply deploy the application to your device for testing. This applies for the ClientConnectionContainer and the SecureClientConnectionContainer.

New version has been published to NuGet. (x.x.x.18)
If you encounter another issue, please open a new ticket, since the original "keySize" related one has been fixed.

Thanks for your help
